export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const APPEND_LIST_ROW = 'APPEND_LIST_ROW';
export const EDIT_LIST_ROW = 'EDIT_LIST_ROW';
export const REMOVE_LIST_ROW = 'REMOVE_LIST_ROW';
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';
export const CLEAR_INPUT_FORM = 'CLEAR_INPUT_FORM';
export const SWITCH_EDIT_MODE = 'SWITCH_EDIT_MODE';

export default {
  SET_INPUT_VALUE,
  APPEND_LIST_ROW,
  EDIT_LIST_ROW,
  REMOVE_LIST_ROW,
  SET_FILTER_VALUE,
  CLEAR_INPUT_FORM,
  SWITCH_EDIT_MODE
};